---
- name: Update package list
  apt:
    update_cache: yes

- name: Install fail2ban if it's not installed
  apt: package=fail2ban state=present

- name: Create jail.local config file
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify:
    - restart fail2ban


